hal: Implement reason of cpu reset flags handling
phoenix-rtos/plo pull request #246
Opened 2023-05-06 19:10 UTC by gerard5

The change adds support for `crf` (CPU reset reason flags) to the i.MXRT and STM32L4 targets. During hal's early boot, the `crf` flags are saved internally to be later displayed in the logs at plo startup later. The functionallity of `crf` logging is to help troubleshoot "suspicious" system reboots.

Flags are printed after cpu info:
```
Phoenix-RTOS loader v. 1.21 rev: 123456
hal: Cortex-M i.MX RT117x (crf=0x08000002)
...
```

And additionally fixes incorrect SRC enums on imxrt117x target.

JIRA: RTOS-455

## Description

## Motivation and Context

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## How Has This Been Tested?

- [ ] Already covered by automatic testing.
- [ ] New test added: (add PR link here).
- [x] Tested by hand on: imxrt1176-nil, imxrt1064-bes, stm32l4a6-nucleo.

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing linter checks and tests passed.
- [ ] My changes generate no new compilation warnings for any of the targets.

## Special treatment

- [ ] This PR needs additional PRs to work (list the PRs, preferably in merge-order).
- [ ] I will merge this PR by myself when appropriate.

2023-05-06 19:11 UTC, gerard5 commented on hal/armv7m/imxrt/117x/imxrt.c
> +	src_gpr16, src_gpr17, src_gpr18, src_gpr19, src_gpr20 };
Nope.

2023-05-08 07:48 UTC, nalajcie requested changes
Unfortunately clearing `SRSR` should not be done as we won't be able to get the boot reason during runtime then (probably we could think of passing bootreason from `plo` to `kernel` in some other way but it seems kind of excessive?)

2023-05-08 07:48 UTC, nalajcie commented on hal/armv7a/imx6ull/imx6ull.c
> +	imx6ull_common.resetFlags = (*(imx6ull_common.ccm + src_srsr) & 0x101fdu);
```suggestion
	imx6ull_common.resetFlags = (*(imx6ull_common.src + src_srsr) & 0x101fdu);
```

2023-05-08 07:48 UTC, nalajcie commented on hal/armv7a/imx6ull/imx6ull.c
> +	*(imx6ull_common.src + src_srsr) = 0xfdu;
Please remove.

The OS needs to read boot reason during / after bootup - **this breaks DTR project**.

Please note that this functionality probably breaks reading reboot reason for other platforms (see the implementation of `pctl_reboot` with action `pctl_get` for various platforms).

2024-05-08 20:01 UTC, gerard5 commented
I'm closing this pull request because there are no plans to use this solution yet.

2024-05-08 20:01 UTC, closed without merging